### ISSUE TITLE
when there is no configuration, the error message should be more explicit

### ISSUE THREAD

**Issue by oupala** [mbrehin/git-precommit-checks#31]
When there is no configuration, the error message should be more explicit than:

> Pre-commit checks failed due to unexpected error. TypeError: Cannot destructure property `patterns` of 'undefined' or 'null'.
>     at run (/home/myuser/path/to/myproject/node_modules/git-precommit-checks/index.js:26:33)

I know configuring is already mentionned in the documentation, but the error message should be clearer.

**Comment by mbrehin** [comment]
You're right, the program should exit after error is logged.  I'm publishing an update.  Thanks for the feedback 👍
