### ISSUE TITLE
"there is no file to check" when amending

### ISSUE THREAD

**Issue by rburgst** [mbrehin/git-precommit-checks#53]
Hi

when I am amending a commit, I get the warning 
```
there is no file to check
```

IMHO it should check all staged files again.

**Comment by mbrehin** [comment]
Hi,

I ran some tests and I didn’t get the behavior you described. Maybe you misunderstood how the process runs: checks are only made on added, copied, modified lines (`﻿﻿﻿git diff --staged --diff-filter=ACM`). If not, would you please give me an example that created that unexpected behavior?

Cheers,

**Comment by rburgst** [comment]
I guess the problem is a misunderstanding. I had a commit where I changed the settings for your plugin. In this commit was already a test file with a FIXME comment. I added the FIXME rule to the config and amended the whole commit.
I thought at this point it would re-check all the files in the commit and flag the FIXME.
It works fine for new commits and you dont change the rules during amending.

**Comment by mbrehin** [comment]
Exactly ! 😃 
Files are not checked twice. If you wanted to rerun the whole checks for your commited files, you'd have to undo the commit (ie `git reset --soft HEAD~1`) and then re-commit.
