### ISSUE TITLE
Ignore files and folders ?

### ISSUE THREAD

**Issue by christophe-glanum** [mbrehin/git-precommit-checks#90]
Salut Maxime,

Est-il possible d'ignorer le contenu d'un dossier ?

Merci !

**Comment by mbrehin** [comment]
Bonjour Christophe, désolé pour le délai de réponse, je n'avais pas vu passer ton message.

Tu peux utiliser le filtre sur nom/chemin de fichier à cet effet : `filter: /^directory\/.*$/,`.

Je me rends compte que le filtrage sur nom de fichiers est très technique. Peut-être que des clés supplémentaires de configuration du type `only` et `exclude` qui prendraient des tableaux de chemins seraient plus utiles. Je me note ça dans un coin.

**Comment by christophe-glanum** [comment]
Merci Maxime, ca fonctionne !

Par contre le dossier que j'ignore peut contenir + de 7000 fichiers et c'est super long ! 😬

J'imagine qu'il vérifie le path de chaque les fichiers par rapport à la règle filter.

Une idée stp ?

Merci !

**Comment by mbrehin** [comment]
Salut @christophe-glanum. Ça mériterait en effet une petite revue du code de ma part pour ne pas boucler sur l'ensemble des fichiers stagés et préfiltrer via la commande Git en amont. 

Bon, en même temps, 7000 fichiers stagés en une fois, c'est quoi ce boulot de goré 😉
