### ISSUE TITLE
Filter does not work

### ISSUE THREAD

**Issue by BryanBerger98** [mbrehin/git-precommit-checks#91]
Hi there!

I am trying to setup `git-precommit-checks` but the rule about `FIXME|TODO` does not work because of the filter.

If I remove the filter it works well, if I set it up the rule seems to be ignored.

I followed the docs and copy/pasted the filter but nothing happens.

Can you help me to find where I did it wrong?

My config:

```json
"git-precommit-checks": {
		"display": {
			"offendingContent": true,
			"rulesSummary": true,
			"verbose": true,
			"shortStats": true
		},
		"rules": [
			{
				"nonBlocking": "true",
				"message": "You've got leftover `console.log`",
				"regex": "^(?!.*//).*console\\.log\\("
			},
			{
				"message": "You've got leftover conflict markers",
				"regex": "/^[<>|=]{4,}/m"
			},
			{
				"filter": "^package\\.json$",
				"message": "You have unfinished devs",
				"nonBlocking": "true",
				"regex": "/(?:FIXME|TODO)/i"
			}
		]
	},
```

Thank you in advance for your help!

**Comment by mbrehin** [comment]
Hi @BryanBerger98. Sorry for the late answer.

I made a mistake in the doc. The example should exclude the `package.json` file : `"filter": "^(?!package\\.json$)"`.
Sorry about that !

**Comment by BryanBerger98** [comment]
Perfect! Thank you!
I am very bad with regex 😅
